app:
  title: Jenkins Example App
  baseUrl: http://localhost:3000

organization:
  name: Jenkins Example

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
    # client: pg
    # connection:
    #   host: 192.168.56.90
    #   port: 5432
    #   user: postgres
    #   password: postgres

integrations:
  github:
    - host: github.com
      token: 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

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  providers:
    github:
      development:
        clientId: Ov23limQyfBw3iaVmPND
        clientSecret: 2585965506dad9b2a48ac1ee8d31ecf152563947
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
        signIn:
          resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName

# proxy:
#   '/jenkins/api':
#     target: 'http://192.168.56.90:8080'
#     changeOrigin: true
#     headers:
#       Authorization: Basic bGV0dXllbjoxMTdhOTI4Mjc0NDU1ZDA5YWZkMTZiMDFjM2U0ZDFjNjhi

jenkins:
  baseUrl: http://192.168.56.90:8080
  username: letuyen
  apiKey: 113d9fc5580b194a1df7b99aa245837e47

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
